MAX_SIZE=9223372036854775807
export HISTFILESIZE=$MAX_SIZE
export HISTSIZE=$MAX_SIZE
export HISTTIMEFORMAT="[%F %T] "
setopt SHARE_HISTORY 
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS

