MAX_SIZE=9223372036854775807
export HISTFILESIZE=$MAX_SIZE
export HISTSIZE=$MAX_SIZE
setopt INC_APPEND_HISTORY
export HISTTIMEFORMAT="[%F %T] "
setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS

